import Head from 'next/head';
import StyledLink from '../components/StyledLink';

export default function Home() {
  return (
    <>
      <Head>
        <title>Space Agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to space agency</h1>
      </main>
    </>
  );
}
