import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <h1>Mini project: wiki?</h1>
        </section>
        <section>
          <p>Section 2</p>
        </section>
        <section>
          <p>Section 3</p>
        </section>
      </main>
    </>
  );
}
